### PR TITLE
Focus color

### PR DESCRIPTION
**Pull request by jackiejakob**
Updated focus indicator for all items to 2px solid dodgerblue (added as variable). 
Updated some demo pages to allow properties to test the focus.

### CODE REVIEW

**Comment by antelopeb** [comment]
@jackiejakob -- can you merge requests again? Thanks!! :)

**Comment by jackiejakob** [comment]
@antelopeb Should be good to go now

**Comment by antelopeb** [comment]
@jackiejakob -- sorry to do this, but I found another bug.

On dropdown, if you keyboard open it right after the page loads, then the focus works perfectly, as expected. However, when you navigate to anther page, the dropdowns no longer receive focus after being opened by keyboard control. There is no longer a way to navigate them with the keyboard.

**Comment by jackiejakob** [comment]
@antelopeb In the demo pages? Is it just the Components dropdown in the header specifically for you or others? I can replicate with the Components dropdown so will look into it this week. Let me know if there are other use cases you saw to debug. Thanks!

**Comment by antelopeb** [comment]
It happens for all the dropdowns anywhere on the page. Thanks!!

**Pull request merged**
