### PR TITLE
Gravity update

### PR DESCRIPTION
**Pull request by jackiejakob**
--update button styles (min-width, disabled state)
--update input styles (border radius, padding, disabled state, drop icon)
--update and add new icons
--fix focus catchall

### CODE REVIEW

**Comment by antelopeb** [comment]
@davodey -- could you take a sec today and check this as well? It looks good to me, but just want a second set of eyes. It is just updating unstable to match Gravity.

@jackiejakob -- did you merge master back in, too?

**Comment by jackiejakob** [comment]
@antelopeb Not yet, still reviewing differences between master and unstable.

**Comment by davodey** [comment]
@jackiejakob Everything looks really good.  I noticed a few icons were not displaying, so you may want to remove these, or figure out the issue.

screen shot 2019-02-19 at 9 14 21 am

**Comment by jackiejakob** [comment]
@antelopeb Brought in changes from master

**Comment by antelopeb** [comment]
Hey @jackiejakob!! I'm looking at this today, sorry for the too long delay.

**Comment by antelopeb** [comment]
Hey @jackiejakob!!! Looks great!

Two questions:
1) Did the templates page change for Gravity at all?
2) The icon buttons look like the text is a bit off centered:
image

**Comment by jackiejakob** [comment]
@antelopeb 
1. Which template pages?
2. Yeah, there's bottom margin on the svgs inside buttons and I wasn't sure why so I didn't want to remove it. I can override it in the dropdown stylesheet so that centers better.

**Comment by antelopeb** [comment]
@jackiejakob -- yeah, you should override that for icons inside buttons so that the formatting stays the same... otherwise, I'm not sure why it would be there either :)

**Comment by jackiejakob** [comment]
@antelopeb Let me know if you see anything else to address. Thanks!

**Comment by mhomolak** [comment]
@antelopeb I see this has been approved for a month+ now.  Can it be merged and released?

**Pull request merged**
