### PR TITLE
Table

### PR DESCRIPTION
**Pull request by sarahvc**
1. Added a11y to sortable table's columns: button with title.
2. Set other columns to unsorted when one column is sorted in table demo page.
3. Fix select functionality in table:
    3.1. behavior inside the table won't affect checkbox outside.
    3.2. check status of the checkbox in thead changes with if or not all rows in tbody are selected.

### CODE REVIEW

**Comment by antelopeb** [comment]
@pauljadam -- can you approve this if it's good on the accessibility front?

**Comment by pauljadam** [comment]
@antelopeb  @sarahvc  The column headers and sorting is correct and accessible but the data table is missing row headers. The cell holding the title text of each row should be a `<th scope="row">` row header. 

Also I would recommend the table have a visible <caption> text as the title of the data table if possible. 

Thanks!

**Comment by sarahvc** [comment]
@pauljadam a11y fixes done. Please review. Thanks for your help!

**Comment by pauljadam** [comment]
@sarahvc There are now row headers but the remaining issues are with the select checkboxes. The first one says Select Row 1 but the 2nd checkbox just says "Select"

Will need to either use aria-label or aria-labelledby.

If there are no visible labels then you can remove the <label> tags also. 

Thanks!

image

**Comment by sarahvc** [comment]
@pauljadam The checkbox won't be clickable if its label is removed. To change this behavior we would need to do some tweaks to the checkbox component. Would it be a problem if we keep the empty labels?

**Comment by antelopeb** [comment]
@sarahvc -- I'm not seeing the table sort in the demo. Are the tables supposed to sort within the demo?

**Comment by sarahvc** [comment]
@antelopeb No, there's no real sorting happening in the demo table. The sorting function was meant to passed in to the table by consumer. I figured we should keep it this way since we don't know what's gonna be the in the table(number? dates? text? ...).

**Comment by sarahvc** [comment]
@antelopeb I think I should have emphasized on this item:
"2. Set other columns to unsorted when one column is sorted in table demo page."

I tried to include the fix on the sorting icon issue into the table component, but the way it's structured I didn't find a good way to do that. I looked into some examples of sortable table built in React I think we probably need to refactor the table component to do that. But I'm not sure if refactoring would affect existing consumers. I figured put it in the demo page provide the consumer an example, and they can incorporate that into the column sorting function which they need to code by themselves anyway.

**Comment by antelopeb** [comment]
@sarahvc -- Sorry, approved already but found one thing I'd like changed!!

On the headers, the entire cell highlights and has a pointer, but I have to click on the text to get it to sort. Can that be changed so that the entire cell is the clickable object? You could do this just by making the link inside a block-level object and moving all the padding, etc, onto it.

**Comment by sarahvc** [comment]
@antelopeb Revised scss and table header class name to make the whole header clickable for sorting buttons in header.

**Pull request merged**
