### PR TITLE
Added a remap to colors variables

### PR DESCRIPTION
**Pull request by sarahvc**
Mapped current colors names into a set of names based on palettes(e.g. $primary: $pe-color-digital-pearson-blue). 
Also updated the demo page of colors to reflect the new naming.

### CODE REVIEW

**Comment by antelopeb** [comment]
Hey all, curious to get your thoughts on this. It's a remapping of the variable names to something more semantic, so that in our own usage we don't have to run around replacing $pe-color-digital-pearson-blue if it's all $primary usage and change over. I know it bit us last time, and in my mind it will make it easier for consuming teams to use our vars for their own CSS as well. This would be only merged into beta for the Huron release.

**Comment by kaadams4** [comment]
We've been wanting to do this for a while! "Huron" seems like a good place to do it.

**Comment by mhomolak** [comment]
Are we thinking design is going to be changing color names frequently? Outside of that I'm not seeing this as adding a ton of benefit.

**Comment by wyseguyonline** [comment]
I'm not sure how a variable named $primary-four is more semantic than $pe-color-white-gray.  Could we please get a use case where this mapping benefits the end developer?

**Comment by kaadams4** [comment]
Well, I think we have had cases in the past where buttons went from blue to lighter blue. Or the App Header change from black to gray to white. But let's say design wants to switch buttons to green. If we have a generic name, we just change the color and the consumers don't have to update anything. Or, we leave the variable name as blue even though the color is actually green.

**Comment by wyseguyonline** [comment]
I understand.  In that case, it seems prudent then to use names like $primary-background or $primary-foreground.  $primary-<number> provides a developer nothing in the way of what is actually going on.  One of our coding standards is to use descriptive variable names.  We wouldn't allow const num3 = 'foo'; and this change seems to follow that pattern.

Considering this use case, it seems prudent to provide a mapping.  However, all our variable names should include some sense of what the variable contains.  This mapping should do the same.

**Comment by kaadams4** [comment]
Maybe a good discussion topic for our next meeting D and D meeting...

**Comment by antelopeb** [comment]
So, the semantics of the color names are in the design usage. $primary means just that, a primary color to use in the scheme. $secondary is a color that can be used as a secondary color in your color scheme, $conditional is to use in cases where you need a conditional color, or one that isn't used that often. I know it's not semantic like "$default-button-background", but it is semantic in terms of design language.

I guess, the big thing is that when you code something, a dev can use more semantic naming conventions in their own SASS, but mapping to $primary is not only beneficial to dev in that they are no long hunting for the color names when they change (we had all the colors change names before and it became a lot of work to refactor just the colors throughout the SDK...), they are just sticking to the vars they already have in place and letting the remappings of $primary, $secondary, etc. get changed; it also will encourage design to make sure they are using colors consistently, as it tells them more explicitly what are primary, secondary and conditional for their design schemes.

**Pull request merged**
