### PR TITLE
fixed disabled primary and cta btns

### PR DESCRIPTION
**Pull request by annehong**
I hope I did this correctly. If not, please let me know and I will fix it right away. Thanks :)

### CODE REVIEW

**Comment by antelopeb** [comment]
Checking with design on the look of disabled buttons.

**Comment by antelopeb** [comment]
@annehong -- let's update per Parker's email. All disabled buttons should look the same.

**Comment by annehong** [comment]
@antelopeb 
Hi Greg,

I made these changes and pushed them but don't see the changes. In case here are the 2 latest commits:

commit c69398b027b94a52c6879a458ce000d7b429f97b
Author: annehong <anne.hong@pearson.com>
Date:   Tue May 22 15:15:55 2018 -0700

    made changes approved by UXF

commit d88a375da6632695991849af4baacf6671fa973a
Author: annehong <anne.hong@pearson.com>
Date:   Tue May 22 14:56:08 2018 -0700

    made all the design changes from UXF

**Comment by antelopeb** [comment]
@annehong -- you committed both to master, not your branch. Please make sure to commit to this branch. I will roll back the changes on master.

**Pull request closed without merging**
