### PR TITLE
Des 895 900

### PR DESCRIPTION
**Pull request by StommePoes**
Various bugz, all in separate commits:
1. Progress Bar Spacing: reduced margin to show ~8px spacing visually between "label" and progress bar track.
2. https://agile-jira.pearson.com/browse/GLP-23193: changed label tag to an output tag, since it's not currently labelling anything anyway, but merely reflecting the current aria-valuetext output. This solves the "hanging label"
3. Added specific cursor for disabled buttons with "link" style, per Dinuka's issue #232 (elements repo)
4. DES-900: when alerts are read as a live region, they're reading out the close button first, simply because it's the first item in source order. Switched the orders, then added some flex styles to re-mimic the design. @umahaea @udhadpa This will require changes in tests while the others might not.

### CODE REVIEW

**Comment by StommePoes** [comment]
Hey Mike if these make it through and everything seems rosy, I'll ping the team who made the ticket and if it works as they want, we can indeed do the same for the standalone.

**Comment by StommePoes** [comment]
Ready for QA I think? @umahaea @udhadpa

**Comment by umahaea** [comment]
@StommePoes -https://github.com/Pearson-Higher-Ed/ux-test-platform/pull/214 for ur review

**Comment by umahaea** [comment]
many approved. good to merge.

**Pull request merged**
